apiVersion: v1
kind: Service
metadata:
  name: rustfs-svc
  namespace: rustfs
  labels:
    app.kubernetes.io/name: rustfs
    app.kubernetes.io/instance: rustfs
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rustfs
    app.kubernetes.io/instance: rustfs
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: console
      port: 9001
      targetPort: 9001
      protocol: TCP
