######################################
# GLOBAL AGENT CONFIG
######################################
[agent]
  interval = "1s"
  flush_interval = "1s"
  precision = "1ms"
  omit_hostname = true
 # logfile = "/var/log/telegraf/telegraf.log"
  debug = false
  quiet = false

###############################################################################
# OUTPUTS
###############################################################################

# Output to console (for debugging)
[[outputs.file]]
  files = ["stdout"]
  data_format = "json"

# Output to PostgreSQL / TimescaleDB
[[outputs.postgresql]]
  connection = "host=192.168.9.136 port=5432 user=postgres password=postgres dbname=postgres sslmode=disable"
  schema = "public"
  tags_as_foreign_keys = false

  # ADD THIS — allows Telegraf to ALTER TABLE when columns are missing
  # schema_updates = ["add-columns"]

  create_templates = [
    '''CREATE TABLE IF NOT EXISTS {{ .table }} (
        time   TIMESTAMPTZ NOT NULL,
        tags   JSONB,
        fields JSONB
    )'''
  ]

###############################################################################
# INPUT PLUGINS
###############################################################################

# System metrics
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false

[[inputs.mem]]
[[inputs.disk]]
  ignore_fs = ["tmpfs","devtmpfs"]
[[inputs.net]]

###############################################################################
# INPUT — CORE NATS (NOT JETSTREAM) with TLS
###############################################################################
[[inputs.nats_consumer]]
  servers = ["nats://192.168.9.133:4222"]
  subjects = ["cc.ivr.call.start","cc.ivr.call.end","cc.report.ivr.rt.*"]
  queue_group = "telegraf_ivr_events"
  data_format = "json"
  secure = true

  ## TLS configuration using CA certificate
  tls_ca = "/etc/telegraf/ca.crt"
  insecure_skip_verify = true
  ## JSON timestamp mapping
  json_time_key = "published_at"
  json_time_format = "2006-01-02T15:04:05.999Z07:00"

  ## JSON fields (string)
  json_string_fields = [
    "event_type",
    "call_id",
    "switch_ip",
    "switch_name",
    "appname",
    "eventAt",
    "call_direction",
    "caller",
    "called",
    "domain",
    "hangup_cause"
  ]

  ## Tag keys
  tag_keys = ["event_type","call_direction","domain"]
  name_override = "ivr_events"
