#!/bin/sh
# =============================================================================
# startup.sh — Admin UI (nginx + Vite static build)
# =============================================================================
# Vite bakes env vars into the JS bundle at BUILD time using import.meta.env.
# Since .env values change per environment, we use runtime injection:
#
# 1. Fix routes + DNS (Multus MacVLAN side effects)
# 2. Fetch all values from Consul KV under admin-frontend/
# 3. Write /usr/share/nginx/html/env-config.js  →  window._env_ = { ... }
# 4. sed-replace build-time placeholder values in compiled JS bundle
# 5. exec nginx -g 'daemon off;'
# =============================================================================

PREFIX="admin-frontend"

# =============================================================================
# BLOCK 0 — FIX ROUTES + DNS
# =============================================================================
echo "[0/4] Pre-flight: fixing routes and DNS..."
ip route add 10.96.0.0/12  via 169.254.1.1 dev eth0 2>/dev/null || true
ip route add 10.244.0.0/16 via 169.254.1.1 dev eth0 2>/dev/null || true
echo "      ✓ Routes fixed"

printf 'nameserver 10.96.0.10\nsearch admin-app.svc.cluster.local svc.cluster.local cluster.local\noptions ndots:5\n' > /etc/resolv.conf
echo "      ✓ DNS restored (CoreDNS: 10.96.0.10)"

CONSUL_URL="${CONSUL_URL}"
CONSUL_TOKEN="${CONSUL_TOKEN}"
# CONSUL_URL / CONSUL_TOKEN are injected by the pod spec from
# .Values.consul.url / .Values.consul.token (see deployment.yaml).
# No hardcoded fallback — fail fast if the pod spec did not inject them.
if [ -z "${CONSUL_URL}" ] || [ -z "${CONSUL_TOKEN}" ]; then
    echo "  ✘  CONSUL_URL/CONSUL_TOKEN not set — check pod env injection" >&2
    exit 1
fi

echo "================================================================="
echo " Admin UI — Startup (nginx)"
echo " Pod: ${POD_NAME:-unknown}"
echo " Consul: ${CONSUL_URL}"
echo "================================================================="

# =============================================================================
# BLOCK 1 — FETCH FROM CONSUL (wget — nginx:alpine has wget, not curl)
# =============================================================================
consul_get() {
    _key="${PREFIX}/${1}"
    _varname="${2}"
    _val=$(wget -qO- \
        --no-check-certificate \
        --timeout=10 \
        --header="X-Consul-Token: ${CONSUL_TOKEN}" \
        "${CONSUL_URL}/v1/kv/${_key}?raw" 2>/dev/null) || true
    if [ -z "${_val}" ]; then
        echo "  ✗ MISSING: ${_key}" >&2
        exit 1
    fi
    export "${_varname}=${_val}"
    echo "  ✓ ${_key}"
}

echo ""
echo "[1/4] Fetching config from Consul (${PREFIX}/)"
echo ""

consul_get "api_base_url"            VITE_API_BASE_URL
consul_get "google_oauth_client_id"  VITE_GOOGLE_OAUTH_CLIENT_ID
consul_get "crypto_secret_key"       VITE_CRYPTO_SECRET_KEY
consul_get "superset_url"            VITE_SUPERSET_URL
consul_get "superset_sdk_domain"     VITE_SUPERSET_SDK_DOMAIN
consul_get "superset_username"       VITE_SUPERSET_USERNAME
consul_get "superset_password"       VITE_SUPERSET_PASSWORD
consul_get "webhook_url"             VITE_WEBHOOK_URL

echo ""
echo "  All keys resolved ✓"

# =============================================================================
# BLOCK 2 — INJECT ENV VARS INTO NGINX HTML
# =============================================================================
echo ""
echo "[2/4] Injecting env vars into nginx HTML..."

NGINX_HTML="/usr/share/nginx/html"

# ── Approach A: window._env_ config file ─────────────────────────────────────
# This file is loaded at runtime by index.html BEFORE the Vite bundle.
# All 8 KV values are written here so window._env_ is always complete.
cat > "${NGINX_HTML}/env-config.js" << ENVEOF
// Auto-generated by startup.sh — DO NOT EDIT
// Source: Consul KV prefix: ${PREFIX}/
// Pod: ${POD_NAME:-unknown}
window._env_ = {
  VITE_API_BASE_URL: "${VITE_API_BASE_URL}",
  VITE_GOOGLE_OAUTH_CLIENT_ID: "${VITE_GOOGLE_OAUTH_CLIENT_ID}",
  VITE_CRYPTO_SECRET_KEY: "${VITE_CRYPTO_SECRET_KEY}",
  VITE_SUPERSET_URL: "${VITE_SUPERSET_URL}",
  VITE_SUPERSET_SDK_DOMAIN: "${VITE_SUPERSET_SDK_DOMAIN}",
  VITE_SUPERSET_USERNAME: "${VITE_SUPERSET_USERNAME}",
  VITE_SUPERSET_PASSWORD: "${VITE_SUPERSET_PASSWORD}",
  VITE_WEBHOOK_URL: "${VITE_WEBHOOK_URL}"
};
ENVEOF
echo "  ✓ env-config.js written (all 8 keys)"

# ── Inject <script src="/env-config.js"> into index.html if not present ───────
# Must come BEFORE the Vite bundle script so window._env_ is ready when
# the app JS executes.
if ! grep -q "env-config.js" "${NGINX_HTML}/index.html" 2>/dev/null; then
    sed -i 's|<head>|<head><script src="/env-config.js"></script>|' "${NGINX_HTML}/index.html"
    echo "  ✓ env-config.js injected into index.html <head>"
else
    echo "  ✓ env-config.js already referenced in index.html"
fi

# ── Approach B: Replace ALL baked-in placeholder values in compiled JS ────────
# Each sed rule targets the exact placeholder string that was baked into the
# Vite bundle at image build time (from your .env.* file).
#
# HOW TO FIND YOUR PLACEHOLDERS:
#   grep -r "localhost\|192\.168\|YOUR_PLACEHOLDER" /usr/share/nginx/html/assets/
#
# Replace the right-hand side strings below with whatever your build .env
# actually contained at docker build time.
# ─────────────────────────────────────────────────────────────────────────────
echo "  Patching compiled JS assets (all 8 KV values)..."

find "${NGINX_HTML}/assets" -name "*.js" 2>/dev/null | while read -r jsfile; do

    # ── VITE_API_BASE_URL ─────────────────────────────────────────────────────
    # Catches any 192.168.x.x:4001 (http or https) baked at build time,
    # plus localhost fallbacks.
    sed -i \
        -e "s|https\?://192\.168\.[0-9]*\.[0-9]*:4001|${VITE_API_BASE_URL}|g" \
        -e "s|http://localhost:4001|${VITE_API_BASE_URL}|g" \
        -e "s|https://localhost:4001|${VITE_API_BASE_URL}|g" \
        "${jsfile}"

    # ── VITE_GOOGLE_OAUTH_CLIENT_ID ───────────────────────────────────────────
    # Replace the build-time placeholder Google OAuth Client ID.
    # Update the pattern below to match your actual build-time value.
    sed -i \
        -e "s|YOUR_BUILD_TIME_GOOGLE_CLIENT_ID\.apps\.googleusercontent\.com|${VITE_GOOGLE_OAUTH_CLIENT_ID}|g" \
        "${jsfile}"

    # ── VITE_CRYPTO_SECRET_KEY ────────────────────────────────────────────────
    sed -i \
        -e "s|NmglZwN3l6PTpGIrxkSihiXQ4YEFE7xCdXQFzR3l3i40l1ffCnmR5|${VITE_CRYPTO_SECRET_KEY}|g" \
        "${jsfile}"

    # ── VITE_SUPERSET_URL ─────────────────────────────────────────────────────
    sed -i \
        -e "s|https\?://192\.168\.[0-9]*\.[0-9]*:8088|${VITE_SUPERSET_URL}|g" \
        -e "s|http://localhost:8088|${VITE_SUPERSET_URL}|g" \
        -e "s|https://localhost:8088|${VITE_SUPERSET_URL}|g" \
        "${jsfile}"

    # ── VITE_SUPERSET_SDK_DOMAIN ──────────────────────────────────────────────
    # Replace the build-time placeholder Superset SDK domain.
    # Update the pattern below to match your actual build-time value.
    sed -i \
        -e "s|YOUR_BUILD_TIME_SUPERSET_SDK_DOMAIN|${VITE_SUPERSET_SDK_DOMAIN}|g" \
        "${jsfile}"

    # ── VITE_SUPERSET_USERNAME ────────────────────────────────────────────────
    # Update the pattern below to match your actual build-time value.
    sed -i \
        -e "s|YOUR_BUILD_TIME_SUPERSET_USERNAME|${VITE_SUPERSET_USERNAME}|g" \
        "${jsfile}"

    # ── VITE_SUPERSET_PASSWORD ────────────────────────────────────────────────
    # Update the pattern below to match your actual build-time value.
    sed -i \
        -e "s|YOUR_BUILD_TIME_SUPERSET_PASSWORD|${VITE_SUPERSET_PASSWORD}|g" \
        "${jsfile}"

    # ── VITE_WEBHOOK_URL ──────────────────────────────────────────────────────
    # Catches any 192.168.x.x or localhost webhook URL baked at build time.
    # Update the pattern below to match your actual build-time value.
    sed -i \
        -e "s|https\?://192\.168\.[0-9]*\.[0-9]*:[0-9]*/webhook|${VITE_WEBHOOK_URL}|g" \
        -e "s|http://localhost:[0-9]*/webhook|${VITE_WEBHOOK_URL}|g" \
        -e "s|YOUR_BUILD_TIME_WEBHOOK_URL|${VITE_WEBHOOK_URL}|g" \
        "${jsfile}"

done
echo "  ✓ Compiled JS assets patched (all 8 KV values)"

# ── Verification ──────────────────────────────────────────────────────────────
echo ""
echo "  Verifying patches..."

check_residual() {
    _pattern="${1}"
    _label="${2}"
    FOUND=$(grep -roh "${_pattern}" "${NGINX_HTML}/assets/" 2>/dev/null | sort -u)
    if [ -n "${FOUND}" ]; then
        echo "  ⚠ WARNING: old ${_label} still found in bundle: ${FOUND}" >&2
    else
        echo "  ✓ No old ${_label} in bundle"
    fi
}

check_residual "https\?://192\.168\.[0-9]*\.[0-9]*:4001"  "API URLs (:4001)"
check_residual "https\?://192\.168\.[0-9]*\.[0-9]*:8088"  "Superset URLs (:8088)"
check_residual "NmglZwN3l6PTpGIrxkSihiXQ4YEFE7xCdXQFzR3l3i40l1ffCnmR5" "crypto_secret_key placeholder"

echo ""
echo "  ── Runtime values injected ─────────────────────────────────────"
echo "    API Base URL         : ${VITE_API_BASE_URL}"
echo "    Google OAuth Client  : ${VITE_GOOGLE_OAUTH_CLIENT_ID}"
echo "    Crypto Secret Key    : (set, not shown)"
echo "    Superset URL         : ${VITE_SUPERSET_URL}"
echo "    Superset SDK Domain  : ${VITE_SUPERSET_SDK_DOMAIN}"
echo "    Superset Username    : ${VITE_SUPERSET_USERNAME}"
echo "    Superset Password    : (set, not shown)"
echo "    Webhook URL          : ${VITE_WEBHOOK_URL}"
echo "  ────────────────────────────────────────────────────────────────"

# =============================================================================
# BLOCK 3 — LAUNCH NGINX
# =============================================================================
echo ""
echo "[3/4] Launching nginx..."
echo "================================================================="

exec nginx -g "daemon off;"
