apiVersion: v1
kind: Secret
metadata:
  name: {{ include "watchdog.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "watchdog.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secret }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
