apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: agnocon-production
  namespace: argocd
  labels:
    agnocon.io/part-of: agnocon
    agnocon.io/env: production
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
        # - service: multus-nad
        #   namespace: multus-nad
        #   wave: "0"
        # - service: mysql-service
        #   namespace: mysql-cluster
        #   wave: "1"
        - service: postgres-service
          namespace: postgres-cluster
          wave: "1"
        # - service: redis-service
        #   namespace: redis
        #   wave: "1"
        # - service: influxdb-service
        #   namespace: influxdb
        #   wave: "1"
        # - service: nats-service
        #   namespace: nats
        #   wave: "1"
        # - service: rustfs-service
        #   namespace: rustfs
        #   wave: "1"
        # - service: fs-core
        #   namespace: freeswitch
        #   wave: "2"
        # - service: rtp-core
        #   namespace: rtpengine
        #   wave: "2"
        # - service: sbc-core
        #   namespace: kamailio
        #   wave: "2"
        # - service: acd-service
        #   namespace: freeswitch
        #   wave: "3"
        # - service: routing-service
        #   namespace: freeswitch
        #   wave: "3"
        # - service: vesl-service
        #   namespace: freeswitch
        #   wave: "3"
        # - service: admin-backend-service
        #   namespace: admin-app
        #   wave: "3"
        # - service: admin-frontend-service
        #   namespace: admin-app
        #   wave: "3"
        # - service: workspace-service
        #   namespace: admin-app
        #   wave: "3"
        # - service: job-service
        #   namespace: observability
        #   wave: "3"
        # - service: grafana-service
        #   namespace: observability
        #   wave: "4"
        # - service: superset-service
        #   namespace: observability
        #   wave: "4"
        # - service: telegraf-service
        #   namespace: observability
        #   wave: "4"
        # - service: watchdog-service
        #   namespace: watchdog
        #   wave: "4"
  template:
    metadata:
      name: "{{.service}}-production"
      labels:
        agnocon.io/part-of: agnocon
        agnocon.io/env: production
        agnocon.io/service: "{{.service}}"
      annotations:
        argocd.argoproj.io/sync-wave: "{{.wave}}"
    spec:
      project: agnocon
      source:
        repoURL: "https://github.com/allwinrajan/gitops-agnocon.git"
        targetRevision: main
        path: "helm/{{.service}}"
        helm:
          releaseName: "{{.service}}"
          valueFiles:
            - values.yaml
            - values-production.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.namespace}}"

      ignoreDifferences:
        - group: apps
          kind: StatefulSet
          jsonPointers:
            - /spec/volumeClaimTemplates/0/apiVersion
            - /spec/volumeClaimTemplates/0/kind

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 5
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
