{{- if .Values.natsBox.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: nats-box-contexts
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: nats-box
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: nats
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  default.json: |
    {
      {{- if .Values.tls.enabled }}
      "url": "tls://{{ .Values.nats.accounts.app.user }}:{{ .Values.nats.accounts.app.password }}@nats:{{ .Values.nats.ports.client }}",
      "tls": {
        "ca_file": "/etc/nats-certs/{{ .Values.tls.ca }}"
      }
      {{- else }}
      "url": "nats://{{ .Values.nats.accounts.app.user }}:{{ .Values.nats.accounts.app.password }}@nats:{{ .Values.nats.ports.client }}"
      {{- end }}
    }
{{- end }}
