apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "freeswitch.labels" . | nindent 4 }}
data:
  startup.sh: |
{{ .Files.Get "configs/startup.sh" | indent 4 }}
  vars.xml.template: |
{{ .Files.Get "configs/templates/vars.xml.template" | indent 4 }}
  xml_curl.conf.xml.template: |
{{ .Files.Get "configs/templates/xml_curl.conf.xml.template" | indent 4 }}
  acl.conf.xml.template: |
{{ .Files.Get "configs/templates/acl.conf.xml.template" | indent 4 }}
  http_cache.conf.xml.template: |
{{ .Files.Get "configs/templates/http_cache.conf.xml.template" | indent 4 }}
