apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.name" . }}-secret
  namespace: {{ include "mysql.namespace" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
stringData:
  root-password: {{ .Values.rootPassword | quote }}
  replication-password: "Repl!c@Int3rnal9"
  {{- range .Values.users }}
  user-{{ .name }}: {{ .password | quote }}
  {{- end }}
