apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.name" . }}-secret
  namespace: {{ include "postgres.namespace" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.postgresPassword | quote }}
  replication-password: "Repl!c@Int3rnal9"
  {{- range .Values.users }}
  user-{{ .name }}: {{ .password | quote }}
  {{- end }}
