#!/bin/sh
# =============================================================================
# startup.sh — Workspace Service (nginx + Vite static build)
# =============================================================================
# Consul KV individual keys under workspace-service/
#
#   workspace-service/config/api-base-url
#   workspace-service/config/google-oauth-client-id
#   workspace-service/config/https-enabled
#   workspace-service/config/https-key-path
#   workspace-service/config/https-cert-path
#   workspace-service/config/iframe-origin
#   workspace-service/secrets/crypto-secret-key
# =============================================================================

PREFIX="workspace-service"
NGINX_HTML="/usr/share/nginx/html"

# =============================================================================
# BLOCK 0 — FIX ROUTES + DNS
# =============================================================================
echo "[0/3] Pre-flight: fixing routes and DNS..."
ip route add 10.96.0.0/12  via 169.254.1.1 dev eth0 2>/dev/null || true
ip route add 10.244.0.0/16 via 169.254.1.1 dev eth0 2>/dev/null || true
echo "      ✓ Routes fixed"

printf 'nameserver 10.96.0.10\nsearch admin-app.svc.cluster.local svc.cluster.local cluster.local\noptions ndots:5\n' > /etc/resolv.conf
echo "      ✓ DNS restored (CoreDNS: 10.96.0.10)"

# Injected by the pod spec from .Values.consul.url / .Values.consul.token
# (see deployment.yaml). No hardcoded fallback.
CONSUL_URL="${CONSUL_URL}"
CONSUL_TOKEN="${CONSUL_TOKEN}"
if [ -z "${CONSUL_URL}" ] || [ -z "${CONSUL_TOKEN}" ]; then
    echo "  ✘  CONSUL_URL/CONSUL_TOKEN not set — check pod env injection" >&2
    exit 1
fi

echo "================================================================="
echo " Workspace Service — Startup (nginx)"
echo " Pod:    ${POD_NAME:-unknown}"
echo " Consul: ${CONSUL_URL}"
echo "================================================================="

# =============================================================================
# BLOCK 1 — FETCH INDIVIDUAL KEYS FROM CONSUL KV
# =============================================================================
consul_get() {
    _key="${PREFIX}/${1}"
    _varname="${2}"
    _val=$(wget -qO- \
        --no-check-certificate \
        --timeout=10 \
        --header="X-Consul-Token: ${CONSUL_TOKEN}" \
        "${CONSUL_URL}/v1/kv/${_key}?raw" 2>/dev/null) || true
    if [ -z "${_val}" ]; then
        echo "  ✗ MISSING: ${_key}" >&2
        exit 1
    fi
    export "${_varname}=${_val}"
    echo "  ✓ ${_key}"
}

echo ""
echo "[1/3] Fetching config from Consul (${PREFIX}/)"
echo ""

consul_get "config/api-base-url"           VITE_API_BASE_URL
consul_get "config/google-oauth-client-id" VITE_GOOGLE_OAUTH_CLIENT_ID
consul_get "config/https-enabled"          VITE_HTTPS
consul_get "config/https-key-path"         VITE_HTTPS_KEY_PATH
consul_get "config/https-cert-path"        VITE_HTTPS_CERT_PATH
consul_get "config/iframe-origin"          VITE_IFRAME_ORIGIN
consul_get "secrets/crypto-secret-key"     VITE_CRYPTO_SECRET_KEY

echo ""
echo "  All keys resolved ✓"

# =============================================================================
# BLOCK 2 — WRITE env-config.js + PATCH index.html + PATCH COMPILED JS BUNDLE
# =============================================================================
echo ""
echo "[2/3] Writing env-config.js, patching index.html and JS bundle..."

# ── A: write window._env_ config file ────────────────────────────────────────
cat > "${NGINX_HTML}/env-config.js" << ENVEOF
// Auto-generated by startup.sh — DO NOT EDIT
// Source: Consul KV prefix: ${PREFIX}/
// Pod: ${POD_NAME:-unknown}
window._env_ = {
  VITE_API_BASE_URL: "${VITE_API_BASE_URL}",
  VITE_GOOGLE_OAUTH_CLIENT_ID: "${VITE_GOOGLE_OAUTH_CLIENT_ID}",
  VITE_CRYPTO_SECRET_KEY: "${VITE_CRYPTO_SECRET_KEY}",
  VITE_HTTPS: "${VITE_HTTPS}",
  VITE_HTTPS_KEY_PATH: "${VITE_HTTPS_KEY_PATH}",
  VITE_HTTPS_CERT_PATH: "${VITE_HTTPS_CERT_PATH}",
  VITE_IFRAME_ORIGIN: "${VITE_IFRAME_ORIGIN}"
};
ENVEOF
echo "  ✓ env-config.js written"

# ── B: inject <script src="/env-config.js"> into index.html ──────────────────
if ! grep -q "env-config.js" "${NGINX_HTML}/index.html" 2>/dev/null; then
    sed -i 's|<head>|<head><script src="/env-config.js"></script>|' "${NGINX_HTML}/index.html"
    echo "  ✓ env-config.js injected into index.html <head>"
else
    echo "  ✓ env-config.js already referenced in index.html"
fi

# ── C: patch compiled JS bundle — replace ALL baked-in API URLs ──────────────
# The Vite bundle bakes the API URL at build time (import.meta.env.VITE_API_BASE_URL).
# window._env_ alone is NOT enough — the bundle uses its own baked value directly.
# We must sed-replace every occurrence of the old IP:port in the compiled assets.
echo ""
echo "  Patching compiled JS assets..."
echo "  Replacing baked-in API URL → ${VITE_API_BASE_URL}"

find "${NGINX_HTML}/assets" -name "*.js" 2>/dev/null | while read -r jsfile; do
    sed -i \
        -e "s|https\?://192\.168\.[0-9]*\.[0-9]*:4001|${VITE_API_BASE_URL}|g" \
        -e "s|http://localhost:4001|${VITE_API_BASE_URL}|g" \
        -e "s|https://localhost:4001|${VITE_API_BASE_URL}|g" \
        "${jsfile}"
done
echo "  ✓ Compiled JS assets patched"

# ── D: verify no old URLs remain ─────────────────────────────────────────────
echo "  Verifying patch..."
FOUND=$(grep -roh "https\?://192\.168\.[0-9]*\.[0-9]*:4001" "${NGINX_HTML}/assets/" 2>/dev/null | sort -u)
if [ -n "${FOUND}" ]; then
    echo "  ⚠ WARNING: old API URLs still found in bundle: ${FOUND}" >&2
else
    echo "  ✓ No old API URLs remain in bundle"
fi

echo ""
echo "  Summary:"
echo "    API     : ${VITE_API_BASE_URL}"
echo "    HTTPS   : ${VITE_HTTPS}"
echo "    Origin  : ${VITE_IFRAME_ORIGIN}"

# =============================================================================
# BLOCK 3 — LAUNCH NGINX
# =============================================================================
echo ""
echo "[3/3] Launching nginx..."
echo "================================================================="

exec nginx -g "daemon off;"
